name: Build CCExtractor on Windows

on:
  push:
    paths:
    - '.github/workflows/build_windows.yml'
    - '**.c'
    - '**.h'
    - 'windows/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
    - '.github/workflows/build_windows.yml'
    - '**.c'
    - '**.h'
    - 'windows/**'

jobs:
  build_non_ocr_release:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2.3.4
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: build Release
      run: msbuild ccextractor.sln /p:Configuration=Release
      working-directory: ./windows
    - name: Display version information
      run: ./ccextractorwin.exe --version
      working-directory: ./windows/Release
    - uses: actions/upload-artifact@v2
      with:
        name: CCExtractor Windows Non-OCR Release build
        path: |
          ./windows/Release/ccextractorwin.exe
          ./windows/Release/*.dll
  build_non_ocr_debug:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2.3.4
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: build Debug
      run: msbuild ccextractor.sln /p:Configuration=Debug
      working-directory: ./windows
    - name: Display version information
      run: ./ccextractorwin.exe --version
      working-directory: ./windows/Debug
    - uses: actions/upload-artifact@v2
      with:
        name: CCExtractor Windows Non-OCR Debug build
        path: |
          ./windows/Debug/ccextractorwin.exe
          ./windows/Debug/ccextractorwin.pdb
          ./windows/Debug/*.dll
  build_ocr_hardsubx_release:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2.3.4
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: install WiX
      run: dotnet tool install --global wix --version 4.0.0-preview.0 &&  wix extension -g add WixToolset.UI.wixext
    - name: Make sure WiX works
      run: wix --version && wix extension -g list
    - name: build Release
      run: msbuild ccextractor.sln /p:Configuration=Release-Full
      working-directory: ./windows
    - name: Display version information
      run: ./ccextractorwinfull.exe --version
      working-directory: ./windows/Release-Full
    - name: Download Flutter GUI
      run: ((Invoke-WebRequest -UseBasicParsing https://api.github.com/repos/CCExtractor/ccextractorfluttergui/releases/latest).Content | ConvertFrom-Json).assets | ForEach-Object {if ($_.name -eq "windows.zip") { Invoke-WebRequest -UseBasicParsing -Uri $_.browser_download_url -OutFile windows.zip}}
      working-directory: ./windows/Release-Full/
    - name: Unzip Flutter GUI
      run: Expand-Archive -Path ./windows.zip -DestinationPath ./
      working-directory: ./windows/Release-Full/
    - name: build installer
      run: wix build -o CCExtractor.msi installer.wxs
      working-directory: ./windows
    - uses: actions/upload-artifact@v2
      with:
        name: CCExtractor Windows OCR and HardSubX Release build
        path: |
          ./windows/Release-Full/*.exe
          ./windows/Release-Full/*.dll
    - uses: actions/upload-artifact@v2
      with:
        name: CCExtractor Windows OCR and HardSubX Release installer
        path: |
          ./windows/CCExtractor.msi
  build_ocr_hardsubx_debug:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2.3.4
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: build Debug
      run: msbuild ccextractor.sln /p:Configuration=Debug-Full
      working-directory: ./windows
    - name: Display version information
      run: ./ccextractorwinfull.exe --version
      working-directory: ./windows/Debug-Full
    - uses: actions/upload-artifact@v2
      with:
        name: CCExtractor Windows OCR and HardSubX Debug build
        path: |
          ./windows/Debug-Full/ccextractorwinfull.exe
          ./windows/Debug-Full/ccextractorwinfull.pdb
          ./windows/Debug-Full/*.dll
